# https://docs.atuin.sh/cli/configuration/config/

search_mode = "skim"
enter_accept = true
style = "auto"
store_failed = false

[sync]
records = true

# https://docs.atuin.sh/cli/guide/theming/
[theme]
name = "default"
